### ISSUE TITLE
Register custom item stacks in GameRegistry

### ISSUE THREAD

**Issue by copygirl** [Azanor/thaumcraft-api#24]
Currently, getting certain items is a bit of a hassle and requires to remember / look up damage IDs for certain sub-items. It'd be useful if you could register custom item stacks within the GameRegistry, so only one line is required to get a specific sub-item, for example thaumium ingots.

Example of a custom item stack being registered:

```java
ItemStack thaumium = new ItemStack(itemResource, 1, 2);
GameRegistry.registerCustomItemStack("ItemIngotThaumium", thaumium);
```

Example of custom item stack being retrieved:

```java
ItemStack thaumium = GameRegistry.findItemStack("Thaumcraft", "ItemIngotThaumium", 1);
```

**Comment by Azanor** [comment]
In theory you can already do that using the oredict (for that specific example at least). Either way, most of my items are moving out of itemResource into their own items for the 1.8 update.
