### ISSUE TITLE
Crash in particle engine

### ISSUE THREAD

**Issue by anion155** [Azanor/thaumcraft-api#30]
Game crash on thaumometr research on shimmerleaf
[https://paste.ee/p/zuzU0](pastebin)

**Comment by anion155** [comment]
Does not happens on beta14

**Comment by ghost** [comment]
Same issue. It crashes when simply selecting the thaumometer. Happens on 6.1.BETA15

Here are the log output:

> [12:45:30] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent@1ed8f90f:
> java.lang.UnsupportedOperationException: null
> 	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176) ~[?:1.8.0_144]
> 	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296) ~[ParticleEngine.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_45_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343) [FMLCommonHandler.class:?]
> 	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1833) [Minecraft.class:?]
> 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186) [Minecraft.class:?]
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:441) [Minecraft.class:?]
> 	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
> 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
> 	at GradleStart.main(GradleStart.java:25) [start/:?]

This are the System infos:

> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 8.1 (amd64) version 6.3
> 	Java Version: 1.8.0_144, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1402007496 bytes (1337 MB) / 1862270976 bytes (1776 MB) up to 3803185152 bytes (3627 MB)
> 	JVM Flags: 0 total; 
> 	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
> 	FML: MCP 9.42 Powered by Forge 14.23.4.2705 18 mods loaded, 18 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State     | ID                   | Version      | Source                                                     | Signature |
> 	|:--------- |:-------------------- |:------------ |:---------------------------------------------------------- |:--------- |
> 	| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                                              | None      |
> 	| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                                              | None      |
> 	| UCHIJAAAA | FML                  | 8.0.99.99    | forgeSrc-1.12.2-14.23.4.2705-PROJECT(Growthcraft-1.12).jar | None      |
> 	| UCHIJAAAA | forge                | 14.23.4.2705 | forgeSrc-1.12.2-14.23.4.2705-PROJECT(Growthcraft-1.12).jar | None      |
> 	| UCHIJAAAA | rustic               | 1.0.5        | Rustic-1.0.5.jar                                           | None      |
> 	| UCHIJAAAA | growthcraft          | 4.0.2.100    | bin                                                        | None      |
> 	| UCHIJAAAA | growthcraft_apples   | 4.0.2.100    | bin                                                        | None      |
> 	| UCHIJAAAA | growthcraft_bamboo   | 4.0.2.100    | bin                                                        | None      |
> 	| UCHIJAAAA | growthcraft_cellar   | 4.0.2.100    | bin                                                        | None      |
> 	| UCHIJAAAA | growthcraft_bees     | 4.0.2.100    | bin                                                        | None      |
> 	| UCHIJAAAA | growthcraft_fishtrap | 4.0.2.100    | bin                                                        | None      |
> 	| UCHIJAAAA | growthcraft_grapes   | 4.0.2.100    | bin                                                        | None      |
> 	| UCHIJAAAA | growthcraft_hops     | 4.0.2.100    | bin                                                        | None      |
> 	| UCHIJAAAA | growthcraft_milk     | 4.0.2.100    | bin                                                        | None      |
> 	| UCHIJAAAA | baubles              | 1.5.2        | Baubles-1.12-1.5.2.jar                                     | None      |
> 	| UCHIJAAAA | thaumcraft           | 6.1.BETA15   | Thaumcraft-1.12.2-6.1.BETA15.jar                           | None      |
> 	| UCHIJAAAA | waila                | 1.8.25       | Hwyla-1.8.25-B40_1.12.jar                                  | None      |
> 	| UCHIJAAAA | jei                  | 4.9.1.190    | jei_1.12.2-4.9.1.190.jar                                   | None      |
> 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.77' Renderer: 'GeForce GTX 970/PCIe/SSE2'
> 	Launched Version: 1.12.2
> 	LWJGL: 2.9.4
> 	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.77, NVIDIA Corporation
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: 
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

**Comment by s0uthw3st** [comment]
Getting the same bug with an almost-identical trace on Beta 15 (but not Beta 14) when using Salis Mundus on blocks - seems like something in the particle generator was broken after Beta 14.
