### ISSUE TITLE
Request: Oredict recipes for infusion crafting

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-api#33]
At the moment infusion crafting can't take oredict entries as input or recipe components. Wanted to use iron ingots in a recipe and welp
Edit: So genius that I am I wrote this before looking deeper into the code. I just assumed it was only item matching because the other addRecipes took Objects for recipe components. Everything in infusion recipes automatically get's matched with the oredict and there's no way of preventing that. For testing purposes I even crafted an arcane bore with oak planks. And I feel dirty now ^^

**Comment by MalkContent** [comment]
Came here to make another isse, found this again.  
To clarify the problem:  
As I see it, you can not NOT make oredict recipes.
The Infusion Recipes don't know oredict entries as components, only ItemStacks, which, when compared for equality during crafting, end up being automatically oredict matched.
You can't i.e. ask for specific wooden planks in a recipe, because later in the item check it will automatically look

**Comment by Azanor** [comment]
Thanks, I'll take a look.

**Comment by Azanor** [comment]
I've changed the way the infusion recipes registry works for the 1.8 update to allow for oredict entries instead of just itemstacks. Automatic matching does not occur anymore as it was causing issues with my own stuff as well. 
Unfortunately it was too big a change to include for 1.7.10.
