### ISSUE TITLE
how to implement the api to workspace?

### ISSUE THREAD

**Issue by matyklug18** [Azanor/thaumcraft-api#35]

**Comment by matyklug18** [comment]
and how to create bauble.

**Comment by FirokOtaku** [comment]
IDEA: File->Project Structrue->Libraries->[+](create a lib)->[+](attach files or dirs to lib 'xxx')->[OK]
Eclipse: (right click your project)->Properties->Java build path->Libraries->Add external jar->..........->[Apply and close]

Create baubles: class NewBauble implements baubles.api.IBauble

**Comment by matyklug18** [comment]
Thanks!

**Comment by Frontrider** [comment]
This structure also works:
https://github.com/Frontrider/thaumic_arcana
