### ISSUE TITLE
Potion effects

### ISSUE THREAD

**Issue by Frontrider** [Azanor/thaumcraft-api#36]
Can the API have a reference to all the potion instances? I have a potion, that would give the player some warp ward as a side effect (among other things), but the only way to get that reference is by going into your internals.

**Comment by Hubry** [comment]
```java
Potion warpWard = Potion.REGISTRY.getObject(new ResourceLocation("thaumcraft:warpward"));
```
From a quick peek at Botania. You could also use Forge's object holders.

**Comment by Frontrider** [comment]
And you're correct.
