### ISSUE TITLE
Use of private functions from OreDictionary.java?

### ISSUE THREAD

**Issue by CovertJaguar** [Azanor/thaumcraft-api#39]
I don't quite understand why this is only an issue in IntellJ and not Netbeans, but I can't compile the API classes without editing the following lines:

https://github.com/Azanor/thaumcraft-api/blob/master/crafting/InfusionRecipe.java#L83
https://github.com/Azanor/thaumcraft-api/blob/master/crafting/InfusionRecipe.java#L83
https://github.com/Azanor/thaumcraft-api/blob/master/crafting/InfusionEnchantmentRecipe.java#L99
https://github.com/Azanor/thaumcraft-api/blob/master/crafting/InfusionEnchantmentRecipe.java#L101

The called OreDictionary functions are all depreciated and scheduled for removal in 1.8 as well.

The error I get is below:
```
Error:(85, 65) java: C:\Users\CovertJaguar\Desktop\Minecraft\Developement\Projects\Railcraft\RailcraftDev\api\thaumcraft\thaumcraft\api\crafting\InfusionRecipe.java:85: getOres(int) has private access in net.minecraftforge.oredict.OreDictionary
Error:(101, 65) java: C:\Users\CovertJaguar\Desktop\Minecraft\Developement\Projects\Railcraft\RailcraftDev\api\thaumcraft\thaumcraft\api\crafting\InfusionEnchantmentRecipe.java:101: getOres(int) has private access in net.minecraftforge.oredict.OreDictionary
```

**Comment by Azanor** [comment]
It works fine in eclipse as well. Very strange.
