### ISSUE TITLE
[Suggestion] Recharge Pedestal improve to Repare Pedestal

### ISSUE THREAD

**Issue by edhelday** [Azanor/thaumcraft-api#40]
The Recharge Pedestal become useless when getting the Vis Amulet, so it could be improved to a Repare Pedestal because the Repare enchant from vanilla MC is very unefficient, specially when using a Elemental Tool (as example Pickaxe of the Core) on a Brain in a Jar. (When right click to extract exp from Brain in a jar, it finds ores, wasting the exp)
The Repare Pedestal could be feeded by Brain in a jar and all exp could be used on reparing the item.

**Comment by AmyMialee** [comment]
You mean making an upgrade to the Recharge Pedestal that can recharge tools with Mending? Or a new Thaumcraft enchantment which is mending but for vis?
Also, it's Repair, and the enchantment is Mending.

**Comment by edhelday** [comment]
Sorry, I play and think in spanish and not a good translator.
I mean the first thing you said.
Implement a new TC enchantment for Mending seems too much. Also repair an item with Mending at pedestal, for vis instead exp.
Maybe the Recharge Pedestal could have the capability without upgrade. But gain it by upgrade sounds well, too.

**Comment by Azanor** [comment]
Please post this in the the suggestions git instead. This is not api related.
