### ISSUE TITLE
Trying to register new FocusUpgradeType causes crash

### ISSUE THREAD

**Issue by SpitefulFox** [Azanor/thaumcraft-api#41]
The code for increasing the cap on the focus upgrade ID array doesn't appear to work.  I receive the following crash on startup:

http://pastebin.com/WULuTyAL

**Comment by SpitefulFox** [comment]
Looks like the last argument for arraycopy should be types.length instead of the new length.

You can see the fix I ended up using on my end here:
https://github.com/SpitefulFox/ForbiddenMagic/blob/master/src/main/java/fox/spiteful/forbidden/items/ForbiddenItems.java#L191

**Comment by Azanor** [comment]
Doh
