### ISSUE TITLE
Iter Aspect is missing

### ISSUE THREAD

**Issue by dredhorse** [Azanor/thaumcraft-api#54]
in https://github.com/Azanor/thaumcraft-api/blob/master/aspects/Aspect.java

**Comment by wamc2017** [comment]
Why is it missing? Iter isn't added by Thaumcraft anymore...

**Comment by dredhorse** [comment]
hmm. strange, the icon in JEI still shows thaumcraft as mod. So i guess every addon can register aspects but ModTweaker can not access those because the api only returns the inbuilt aspects?

**Comment by wamc2017** [comment]
I think Thaumic Bases Unofficial is adding Iter back in. ;)
Also Thaumic JEI is adding those icons for every aspect in JEI, so also not a TC problem here, I guess...

**Comment by dredhorse** [comment]
I have thaumic bases, but in this case the api is lacking. Thaumcraft itself is able to process all those aspects, so I should be able to retrieve all those aspects too. my 2 cents :-)

I would need to get the sourcecode of all 3 projects (thaumcraft, ModTweaker and Thaumic Bases) down and fire up my ide to figure out who the culprit is. 

Do you have any idea?

**Comment by wamc2017** [comment]
Thaumic Bases doesn't use the AspectRegistryEvent and registers the aspects in Post Init (which is too late for crafttweaker to pick them up)...
I already told this the author [some time ago](https://github.com/Rumaruka/Thaumic-Bases-Unofficial/issues/7#issuecomment-423514823)...

**Comment by dredhorse** [comment]
well than we have the culprit or? :-)
