### ISSUE TITLE
Edit: team cofh is on it.

### ISSUE THREAD

**Issue by Plaer1** [Azanor/thaumcraft-api#65]
Soon™

**Comment by mechanikate** [comment]
I really think this would be the best way to get TC going again ^^^

**Comment by MrVauxs** [comment]
After 2 years, it would be really beneficial for the mod to become truly open-source.

**Comment by tabr** [comment]
Do we need to create a petition to make em open-source?

**Comment by Plaer1** [comment]
> Do we need to create a petition to make em open-source?

Nah I feel like reaching out and being polite about it is for sure the best way to handle this.

**Comment by eliskvitka** [comment]
+1 for open source
Or you can give permission to decompile your mod

**Comment by Angular-Angel** [comment]
Yeah I would love access to the Thaumcraft source. This mod was amazing, it'd be great to see someone bring it back.

**Comment by vlad2305m** [comment]
Love Thaumcraft 4 the best. Could you please release the code of the old versions so that people can update them to Fabric?
